[package]
name = "jeff-mitchell-dev"
version = "0.7.1"
edition = "2021"
publish = false

[[bin]]
name = "jeff-mitchell-dev"
path = "src/bin/main.rs"

[lib]
name = "jeff_mitchell_dev_lib"
path = "src/lib/lib.rs"

[dependencies]
rocket = "0.5.1"
shuttle-rocket = "0.47.0"
shuttle-runtime = "0.47.0"
