[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.trunk-serve]
description = "Builds the site in dev mode using trunk serve --open"
script = [
  "cargo clean",
  "cd ~/dev/source/repos/jeff-mitchell-dev/site",
  "trunk serve --open"
]

[tasks.build-shuttle-local]
description = "Builds the site in release mode with trunk build --release, then deploys the site locally with cargo shuttle run"
script = [
  "cargo clean",
  "cd ~/dev/source/repos/jeff-mitchell-dev/site",
  "trunk build --release",
  "cd ../server",
  "cargo shuttle run"
]

[tasks.build-shuttle-remote]
description = "Builds the site in release mode with trunk build --release, then deploys the site to the shuttle build cluster for deployment"
script = [
  "cargo clean",
  "cd ~/dev/source/repos/jeff-mitchell-dev/site",
  "trunk build --release",
  "cd ../server",
  "cargo shuttle deploy"
]

[tasks.serve-dev]
dependencies = [
  "trunk-serve"
]

[tasks.deploy-shuttle-local]
dependencies = [
  "build-shuttle-local"
]

[tasks.deploy-shuttle-remote]
dependencies = [
  "build-shuttle-remote"
]