# The URL the site will be built for
base_url = "https://jeff-mitchell-dev.shuttleapp.rs"

# title
title = "jeff-mitchell.dev"

# description
description = "A blog mostly about Rust...mostly..."

# enable the zern theme
theme = "zerm"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Taxonomies configuration
taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
hightlight_theme = "dracula"

# enable RSS Feed
generate_feed = true
feed_filename = ["rss.xml"]

# open external links in a new tab
external_links_target_blank = true

# set rel="noreferrer" for all external links
external_links_no_referrer = true

[extra]
# Put all your custom variables here
author = "Jeff Mitchell"
show_author = true
theme_color = "orange"
center = true
show_categories = true
show_tags = true
logo_text = "jeff-mitchell.dev :: mis-adventures with the Rust programming language"
logo_home_link = "/"
copyright = "Copyright &copy; 2024 Jeffery D. Mitchell :: Powered by Zola :: Hosted on Shuttle"
main_menu = [
  { url = "@/_index.md", name = "home" },
  { url = "@/about/_index.md", name = "about" },
  { url = "/categories", name = "categories" },
  { url = "/tags", name = "tags" },
  { url = "/projects", name = "projects" },
  { url = "/resources", name = "resources"},
  { url = "https://github.com/sentinel1909", name = "GitHub", external = true },
  { url = "https://query.rs", name = "query.rs", external = true }
]

read_more = "read"